# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
cache: cocoapods
xcode_project: Example/RTRootNavigationController.xcworkspace
xcode_scheme: RTRootNavigationController-Example
podfile: Example/Podfile
before_install:
- cd Example
- pod update
script:
- pod lib lint
